services:
  db:
    image: mariadb:11.6.2
    container_name: 'db-mariadb-s7'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/.database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    container_name: 'db-interface-phpmyadmin-s7'
    depends_on:
      - db
    ports:
      - "8000:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: 'symfony-s7'
    ports:
      - "8080:80"
    depends_on:
      - db
      - maildev
    user: "1000:1000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./docker/php.ini:/usr/local/etc/php/conf.d/more_upload_size.ini
      - .:/var/www/html
  maildev:
    image: maildev/maildev:1.1.0
    container_name: 'maildev-s7'
    ports:
      - "8081:80"
      - "25:25"
